version: '3.8'

services:
  # Development database
  dev-db:
    image: mysql:8.0
    container_name: db_dev
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - dev_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - db_network

  # Test database
  test-db:
    image: mysql:8.0
    container_name: db_test
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - test_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - db_network

# Volumes for persistence
volumes:
  dev_data:
  test_data:

# Networks
networks:
  db_network:
